project:
  type: book
  output-dir: docs

book:
  title: "Personal Science Cookbook"
  author: "Friends of Personal Science"
  subtitle: "Practical techniques to apply scientific principles to your own life."
  date: last-modified
  downloads: [epub, pdf, docx]
  chapters:
    - index.qmd
    - part: "General Overview"
      chapters:
        - intro.qmd
        - 02-literature.qmd
    - part: "Techniques"
      chapters:
        - get-started.qmd
        - method.qmd
        - 04-application.qmd
        - playN-of-1.qmd
    - 05-summary.qmd
    - Excelttest.qmd
    - 06-references.qmd

bibliography:
  - book.bib

extract-media: "assets/images"
license: "MIT"


format:
  html:
    theme: litera
    toc: true
    css: css/normalize.css
  pdf:
    documentclass: scrreprt
  epub:
    css: css/normalize.css


editor: visual
