project:
  type: book
  output-dir: docs
  preview: 
      port: 4200

execute:
  cache: true
  freeze: auto

book:
  title: "Personal Science Cookbook"
  subtitle: "Practical techniques to apply scientific principles to your own life."
  date: last-modified
  cover-image: assets/coverCookbook-quarto.jpg
  downloads: [epub, pdf, docx]
  chapters:
    - index.qmd
    - part: "General Overview"
      chapters:
        - intro.qmd
        - personal_science.qmd
    - part: "Techniques"
      chapters:
        - get-started.qmd
        - method.qmd
        - applications.qmd
        - microbiome.qmd
        - playN-of-1.qmd
    - summary.qmd
    - Excelttest.qmd
    - references.qmd

bibliography:
  - book.bib

extract-media: "assets/images"
license: "MIT"


format:
  html:
    theme: litera
    code-fold: true
    toc: true
    css: css/theme.css
    df-print: paged
    cover-image: assets/coverCookbook-quarto.jpg
  pdf:
    documentclass: scrreprt
    title: Personal Science Cookbook
    include-before-body: assets/coverpage.txt
  epub:
    css: css/theme.css


editor: visual
